application: weatherforcastsms
version: 2
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: .*
  script: main.app
  login: admin

libraries:
- name: webapp2
  version: "2.5.1"
- name: lxml
  version: "2.3"

builtins:
- admin_redirect: on
